baseURL = 'https://i-ship.github.com/'
languageCode = 'en-us'
title = 'Notes from fields'

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-relearn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]